# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'karpathy/nanoGPT'
        path: 'nanogpt'
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install torch numpy transformers datasets tiktoken wandb tqdm

    - name: Run
      working-directory: 'nanogpt'
      run: |
        python data/shakespeare_char/prepare.py
        python train.py config/train_shakespeare_char.py --device=cpu --compile=False --eval_iters=20 --log_interval=1 --block_size=64 --batch_size=12 --n_layer=4 --n_head=4 --n_embd=128 --max_iters=2000 --lr_decay_iters=2000 --dropout=0.0
        python sample.py --out_dir=out-shakespeare-char --device=cpu

    - name: Run
      working-directory: 'nanogpt/out-shakespeare-char'
      run: |
        ls
        
        

